Style category page
Code4HR/okcandidate-platform pull request #128
Opened 2017-05-31 22:52 UTC by wbprice

<img width="343" alt="screen shot 2017-05-31 at 6 52 17 pm" src="https://cloud.githubusercontent.com/assets/2590422/26657506/4ba899de-4632-11e7-8353-7354bfa1dc06.png">

2017-06-03 22:27 UTC, ttavenner requested changes
Page looks good. Just one small fix formatting fix needed.

2017-06-03 22:27 UTC, ttavenner commented on frontend/js/components/organisms/CategoryListItem.js
> +
Trailing spaces on this line cause `npm test` to fail

2017-06-05 16:25 UTC, qwo approved these changes

2017-06-05 16:29 UTC, wbprice commented
@ttavenner The style issue was fixed.

2017-06-05 16:30 UTC, ttavenner approved these changes

2017-06-05 16:30 UTC, merged