adding random passphrase generation on new created surveyresults
Code4HR/okcandidate-platform pull request #141
Opened 2017-06-22 03:01 UTC by stanzheng

2017-06-25 21:39 UTC, rydente commented
Tests?

2017-07-02 15:54 UTC, ttavenner requested changes

2017-07-02 15:54 UTC, ttavenner commented on api/controllers/SurveyController.js
> +module.exports = class SurveyResultController extends Controller {
This should be in SuveyResultController.

2017-07-02 15:54 UTC, ttavenner commented on api/controllers/index.js
> +exports.SurveyResultController = require('./SurveyController');
Should point at SurveyResultController

2017-07-02 15:54 UTC, ttavenner commented on api/services/SurveyResultService.js
> +"use strict";
Make sure you have pulled in the most recent changes, this file already exists and has several functions.

2017-07-02 15:54 UTC, ttavenner commented on api/services/index.js
> +exports.SurveyResultService = require('./SurveyResultService');
Make sure you have the most recent changes, this line already exists as well as another line.

2017-07-02 15:54 UTC, ttavenner commented on config/routes.js
> +        path: '/api/v1/survey',
This should be on the `surveyresult` route rather than the `survey` route.

2017-07-05 00:13 UTC, stanzheng commented on api/controllers/SurveyController.js
> +module.exports = class SurveyResultController extends Controller {
👍

2017-07-05 00:13 UTC, stanzheng commented on api/controllers/index.js
> +exports.SurveyResultController = require('./SurveyController');
👍

2017-07-05 00:22 UTC, stanzheng commented
@rydente  good point will add tests

@ttavenner merged up stream thanks for that hint. 

There are also a few broken jshint rules that ill need to also patch.

2017-07-17 01:20 UTC, stanzheng commented
came back and added a test here @rydente 

https://github.com/Code4HR/okcandidate-platform/pull/141/commits/3edd36f086f1eabcd6a441d5953afeaf6db077c9

otherwise nothing too much changed.

2017-07-20 01:14 UTC, stanzheng commented
addressed all your changes @ttavenner :)

2017-07-20 01:59 UTC, ttavenner commented
The API tests currently fails when running `npm test` because it expects the API to already be running.

2017-07-22 21:31 UTC, stanzheng commented
this doesn't fail for me locally. Does it fail on codeship @ttavenner ? How can i have the build run manually curious don't see it.

2017-07-23 16:12 UTC, ttavenner commented
There is no way to run it manually on Codeship @stanzheng, it won't build off of forks. However since it is running the test using `npm test` in a linux container there is a high likelihood it will have the same result as my environment. Are you running at `npm test` with the server running in the background? If I do that it passes but if I run `npm test` without starting the server it fails with the following error:

```
SurveyResultController generate a public and private passphrase:
     TypeError: Cannot read property 'status' of undefined
      at Test._assertStatus (node_modules/supertest/lib/test.js:229:10)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:687:12)
      at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:639:10)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

2017-07-23 22:30 UTC, stanzheng commented
@ttavenner so i dunno, it seems like on first run, while the service is starting up its down but waiting a while it actually hits the  live service. 

Probably the wrong way to test this. I can remove it to get the pull in. 

@ryayak1460 @rydente might have a better suggestion how to test this.

2017-07-24 15:39 UTC, rydente commented
If you really want to run an integration test, you'll need to start the service and wait til it starts in the `npm test` command.

Otherwise, I'd suggest writing unit tests instead.  They won't require the service to run at all.  You could mock dependencies with a library, possibly [Sinon](http://sinonjs.org/).

2017-07-26 03:52 UTC, stanzheng commented
ok test fixed @wbprice mergy mergy.

2017-07-26 04:41 UTC, stanzheng commented
the failed build is from the HR file change. thats weird.

2017-07-27 00:23 UTC, wbprice commented
I don't know.  It could be some kind of caching in CI.  @ttavenner

2017-07-27 03:24 UTC, closed without merging