New survey tool
Code4HR/okcandidate-platform pull request #164
Opened 2017-07-21 23:20 UTC by wbprice

A tool for creating new surveys.  To test manually, open `/admin/survey/new`

2017-07-23 16:20 UTC, ttavenner requested changes
You have some linting errors. This also breaks the sequence fix on the fixture data I added because it removes the ids.

2017-07-24 02:16 UTC, wbprice commented
So many linting errors!

2017-07-24 13:43 UTC, wbprice commented
Updated

2017-07-24 14:36 UTC, ttavenner approved these changes

2017-07-24 14:36 UTC, merged