Add a freeform text field for name.
Code4HR/okcandidate-platform pull request #232
Opened 2017-08-21 19:21 UTC by wbprice

If user wants to subscribe to the newsletter, require that name and
email address be provided.

Fixes #231

2017-08-21 19:43 UTC, stanzheng commented on frontend/js/redux/actions/result-actions.js
> +        payload.name && (body.name = payload.name);
whats the difference between this and just assigning it directly to body in declaration?

2017-08-21 19:56 UTC, wbprice commented on frontend/js/redux/actions/result-actions.js
> +        payload.name && (body.name = payload.name);
This is to get around an oddity in Joi validation.  Undefined or a blank string is considered to be a valid string by `Joi.string()`.

2017-08-22 19:43 UTC, ttavenner requested changes
The `electionReminder` function in `SurveyResultController` is currently missing the name field.

2017-08-23 00:49 UTC, ttavenner approved these changes

2017-08-23 00:49 UTC, merged