Additional checks that prevent a page from re-rendering unnecessarily
Code4HR/okcandidate-platform pull request #259
Opened 2017-09-09 19:03 UTC by ttavenner

Prevents changes to state in `componentWillMount` from triggering multiple unnecessary re-renders.

2017-09-10 18:06 UTC, wbprice commented
This seems fine.  Have you noticed that a new record is created when the user visits the results page too?

2017-09-10 22:53 UTC, ttavenner commented
@wbprice No new records were created on the results page but it was calling the match service multiple times for the same reason as the other pages. I cleaned this up. I also removed what seemed to be an unnecessary second query of survey result in componentWillMount on the results page. So let me know if that needs to be there for some other functionality. Specifically:

```javascript
componentWillMount() {
    this.props.dispatch(fetchSurveyResults(this.props.params.passPhrase));
    this.props.dispatch(fetchSurveyResult());
}
```
becomes
```javascript
componentWillMount() {
    if (this.props.result.matches.length === 0) {
        this.props.dispatch(fetchSurveyResults(this.props.params.passPhrase));
    }
}
```

2017-09-14 01:17 UTC, wbprice commented on frontend/js/components/environments/Results.js
>      componentWillMount() {
`componentWillMount` is called on the server and in the client.  `componentDidMount` is only called in the client.  Did you mean to put this in that hook?

2017-09-14 01:18 UTC, wbprice commented on frontend/js/components/environments/Survey.js
> +        if (!this.props.survey.SurveyResultId) {
The logic for this should be:
```
If the user asks for a new survey OR a survey result is not defined THEN
do the stuff
```

2017-09-14 01:20 UTC, wbprice requested changes
Pull in these fixes to prevent a reference error when rendering on the server. https://github.com/ttavenner/okcandidate-platform/pull/2

2017-10-18 23:09 UTC, wbprice approved these changes

2017-10-18 23:10 UTC, merged