Configure nginx proxy to split api/app traffic
Code4HR/okcandidate-platform pull request #270
Opened 2018-03-30 01:33 UTC by wbprice

2018-04-02 13:04 UTC, stanzheng commented on reverse-proxy/nginx.conf
> +events { worker_connections 1024; }
for a setting with only one option you don't need the braces so i would rewrite 
`events  worker_connections 1024;`

2018-04-02 13:04 UTC, stanzheng commented on reverse-proxy/nginx.conf
> +worker_processes 1;
For this I think its suggested to run it as "auto"
Hard coding 1 sound wrong but I can't find docs to what a proper node configuration would be

2018-04-02 13:04 UTC, stanzheng commented on reverse-proxy/nginx.conf
> +worker_processes 1;
see where for 
`worker_processes auto;`
https://gist.github.com/denji/8359866

2018-04-02 17:02 UTC, BretFisher requested changes
1. no need to build proxy image for local dev, just use default nginx image and use volumes to bind-mount the conf into it at runtime. 
2. likely no need to edit `/etc/nginx/nginx.conf`, but rather bind-mount over the default site config to make it much easier: `/etc/nginx/conf.d/default.conf`. Look at that file in container to see example (it's just the `server{}` part).

2018-04-06 02:38 UTC, wbprice commented
@BretFisher @stanzheng updated

2018-04-08 03:51 UTC, stanzheng commented
LGTM and the request @BretFisher requested.

2018-04-08 22:41 UTC, merged