Include Cucumber.js dependencies
Code4HR/okcandidate-platform pull request #94
Opened 2017-04-14 17:06 UTC by rydente

Include Cucumber.js and Zombie.js so we can provide a common language
for discussing and understanding the OkCandidate Platform, along with a
means of automatically verifying everything still works according to
plan.

Signed-off-by: Ryan Y <ryayak1460@protingumas.com>

2017-04-14 17:06 UTC, rydente commented
[An example](https://gist.github.com/rydente/1d8750853a814e8e7901a86a80cc04a6) of how specifications would look with Cucumber.js and Zombie.js.

2017-04-15 15:46 UTC, wbprice commented
How does this work with Codeship?

2017-04-15 16:35 UTC, wbprice requested changes
Do some research into how this plugs into Codeship w/ @ttavenner

2017-04-15 17:26 UTC, wbprice approved these changes

2017-04-15 17:26 UTC, merged